#!/usr/bin/env python3
"""
Sync Zone Data Script

Generates zone_data.js from zone_analysis.json to keep the dashboard in sync.

This script bridges the gap between:
- docs/data/zone_analysis.json (generated by generate_zone_dashboard_data.py)
- DELIVERABLES/dashboards/zone_data.js (consumed by dashboard HTML)

For GitHub Pages: Also copies to docs/ for serving alongside index.html

Usage:
    python3 scripts/sync_zone_data.py

Run this after:
    python3 scripts/generate_zone_dashboard_data.py
"""

import json
import shutil
from datetime import datetime
from pathlib import Path

# Paths
PROJECT_ROOT = Path(__file__).parent.parent
SOURCE_JSON = PROJECT_ROOT / "docs" / "data" / "zone_analysis.json"
OUTPUT_JS = PROJECT_ROOT / "DELIVERABLES" / "dashboards" / "zone_data.js"
GITHUB_PAGES_JS = PROJECT_ROOT / "docs" / "zone_data.js"  # For GitHub Pages

# Dashboard files for GitHub Pages
DASHBOARD_HTML = PROJECT_ROOT / "DELIVERABLES" / "dashboards" / "dinneroo_master_dashboard.html"
GITHUB_PAGES_DASHBOARD = PROJECT_ROOT / "docs" / "dashboard.html"


def load_zone_analysis():
    """Load the zone analysis JSON."""
    if not SOURCE_JSON.exists():
        print(f"✗ Source not found: {SOURCE_JSON}")
        print("  Run: python3 scripts/generate_zone_dashboard_data.py first")
        return None
    
    with open(SOURCE_JSON, 'r') as f:
        data = json.load(f)
    
    return data


def generate_zone_data_js(data: dict) -> str:
    """Generate JavaScript file content from zone analysis data."""
    # Extract just the zones array and summary/methodology for the dashboard
    # This keeps the JS file focused on what the dashboard needs
    
    dashboard_data = {
        "zones": data.get("zones", []),
        "methodology": data.get("methodology", {}),
        "summary": data.get("summary", {})
    }
    
    # Count zones with orders for the header comment
    zones_with_orders = len([z for z in dashboard_data["zones"] if z.get("orders", 0) > 0])
    
    # Generate JS content
    js_content = f"""// Zone analysis data - {zones_with_orders} zones with orders
// Auto-generated from docs/data/zone_analysis.json
// Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
// DO NOT EDIT MANUALLY - Run: python3 scripts/sync_zone_data.py

const zoneAnalysisDataEmbedded = {json.dumps(dashboard_data, separators=(',', ':'))};
"""
    
    return js_content


def main():
    print("=" * 60)
    print("SYNCING ZONE DATA")
    print(f"Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)
    print()
    
    # Load source data
    print(f"Loading: {SOURCE_JSON.name}")
    data = load_zone_analysis()
    
    if data is None:
        return False
    
    zones_count = len(data.get("zones", []))
    zones_with_orders = len([z for z in data.get("zones", []) if z.get("orders", 0) > 0])
    print(f"  ✓ Loaded {zones_count} zones ({zones_with_orders} with orders)")
    print()
    
    # Generate JS content
    print("Generating zone_data.js...")
    js_content = generate_zone_data_js(data)
    js_size_kb = len(js_content) / 1024
    print(f"  ✓ Generated {js_size_kb:.1f} KB")
    print()
    
    # Write to dashboard directory
    print(f"Writing: {OUTPUT_JS}")
    OUTPUT_JS.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_JS, 'w') as f:
        f.write(js_content)
    print(f"  ✓ Written to DELIVERABLES/dashboards/")
    
    # Copy to docs/ for GitHub Pages
    print(f"Writing: {GITHUB_PAGES_JS}")
    with open(GITHUB_PAGES_JS, 'w') as f:
        f.write(js_content)
    print(f"  ✓ Written to docs/ (GitHub Pages)")
    
    # Copy dashboard HTML to docs/ for GitHub Pages
    if DASHBOARD_HTML.exists():
        print(f"Copying: dashboard.html to docs/")
        shutil.copy(DASHBOARD_HTML, GITHUB_PAGES_DASHBOARD)
        print(f"  ✓ Dashboard copied to docs/ (GitHub Pages)")
    
    print()
    print("=" * 60)
    print("SYNC COMPLETE")
    print("=" * 60)
    print()
    print("Files updated:")
    print(f"  • {OUTPUT_JS.relative_to(PROJECT_ROOT)}")
    print(f"  • {GITHUB_PAGES_JS.relative_to(PROJECT_ROOT)}")
    print(f"  • {GITHUB_PAGES_DASHBOARD.relative_to(PROJECT_ROOT)}")
    print()
    print("Data summary:")
    print(f"  • Total zones: {zones_count}")
    print(f"  • Zones with orders: {zones_with_orders}")
    mvp_breakdown = data.get('summary', {}).get('mvp_status_breakdown', data.get('summary', {}).get('mvp_status', {}))
    print(f"  • MVP Ready: {mvp_breakdown.get('MVP Ready', 0)}")
    print(f"  • Near MVP: {mvp_breakdown.get('Near MVP', 0)}")
    print(f"  • Progressing: {mvp_breakdown.get('Progressing', 0)}")
    print()
    
    return True


if __name__ == "__main__":
    success = main()
    exit(0 if success else 1)

